import { Box } from '@mui/material'
import Head from 'next/head'
import Footer from './Footer'
import Navigation from './Navigation/Navigation'
import { ScrollToTop } from './BackToTop'

const Layout = ({ children }: { children: React.ReactNode }) => {
  return (
    <>
      <Head>
        {/* Title */}
        <title>dream lab</title>
        {/* Description */}
        <meta name="description" content="Generated by create next app" />
        {/* Responsive Meta Tag - Mui */}
        <meta name="viewport" content="initial-scale=1, width=device-width" />
        {/* Favicon */}
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navigation />
      <Box sx={{ width: '100%' }}>
        <main className="main-container">{children}</main>
      </Box>
      <ScrollToTop />
      <Footer />
    </>
  )
}

export default Layout
