import type { NextPage } from 'next'
import Head from 'next/head'

/* Components */
import Navigation from '../components/Navigation'
import Agentur from '../components/Agentur'
import Team from '../components/Team'
import Kontakt from '../components/Kontakt'
import Footer from '../components/Footer'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        {/* Title */}
        <title>dream lab</title>
        {/* Description */}
        <meta name="description" content="Generated by create next app" />
        {/* Responsive Meta Tag - Mui */}
        <meta name="viewport" content="initial-scale=1, width=device-width" />
        {/* Favicon */}
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Navigation */}
      <Navigation />
      {/* Components Content */}
      <Agentur />
      <Team />
      <Kontakt />
      {/* Footer */}
      <Footer />
    </div>
  )
}

export default Home
