import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'

/* Components */
import Navigation from '../components/Navigation'
import Agentur from '../components/Agentur'
import Projekt from '../components/Projekt'
import Team from '../components/Team'
import Kontakt from '../components/Kontakt'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        {/* Title */}
        <title>dream lab</title>
        {/* Description */}
        <meta name="description" content="Generated by create next app" />
        {/* Responsive Meta Tag - Mui */}
        <meta name="viewport" content="initial-scale=1, width=device-width" />
        {/* Favicon */}
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Navigation */}
      <Navigation />
      {/* Components Content */}
      <div style={{ position: 'relative' }}>
        <Agentur />
        <Team />
      </div>
      {/*        <Projekt /> */}
      {/*     <Kontakt />

      <footer className={styles.footer}></footer> */}
    </div>
  )
}

export default Home
